# Generated by Django 2.2.4 on 2020-02-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Task', models.CharField(max_length=50)),
                ('TimeStart', models.TimeField()),
                ('TimeEnd', models.TimeField()),
                ('OnWorkFlag', models.IntegerField()),
            ],
        ),
    ]
