# Generated by Django 2.2.4 on 2020-02-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrackTool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task',
            new_name='TaskName',
        ),
    ]
