# Generated by Django 2.2.4 on 2020-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrackTool', '0002_auto_20200224_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='OnWorkFlag',
            field=models.IntegerField(null=True),
        ),
    ]
